### ISSUE TITLE
Running simpleBeacon.js error?

### ISSUE THREAD

**Issue by gkodikara** [don/node-eddystone-beacon#10]
Hi there

I'm running - 
    sudo node simpleBeacon.js

And get the following error - 
    Error: Cannot find module './../eddystone-beacon'...

What am I doing wrong - everything is in the right place as I've done sudo npm install eddystone-beacon, etc.

**Comment by dermike** [comment]
@gkodikara There's a missing dot... should be '../../eddystone-beacon'
Fixed with this PR don/node-eddystone-beacon/pull/11

**Comment by sandeepmistry** [comment]
This is fixed now, I've merged in #11 from @dermike.
