### ISSUE TITLE
Does not work with Google iOS sample App

### ISSUE THREAD

**Issue by fvisticot** [don/node-eddystone-beacon#13]
When I try this sample code with my Mac and my iPhone using the Google sample App (objC)
I get this error on the smartphone:

EddystoneScannerSample[1306:370661] Unsupported frame type (0) detected. Ignorning.

**Comment by christopherdro** [comment]
This issue seems related to the iOS. The example App provides a version in Swift, try building that one.

I'll loop back with more when I get a chance to look at it further

**Comment by christopherdro** [comment]
Looks like sample project provided by google is scanning for UID frame types. while this project is advertising a URL frame type.

**Comment by christopherdro** [comment]
This is can be closed and tracked further here.
https://github.com/google/eddystone/issues/30

**Comment by sandeepmistry** [comment]
@christopherdro thanks for looking into this!

@fvisticot I'm closing this as per @christopherdro suggestion above. This repo will eventually have an API for Eddystone-UID beacon types.
