### ISSUE TITLE
Advertising error

### ISSUE THREAD

**Issue by dermike** [don/node-eddystone-beacon#15]
Just discovered a weird advertising(?) error I cannot figure out myself.

I'm trying to advertise this shortened url (a personalised bitly domain):
http://nigh.pw/1LPkaFc
but it doesn't get picked up by any Physical Web scanner.

If I change it to:
http://bit.ly/1LPkaFc
it works. 

The actual eddystone URL data looks the same after encoding and decoding, so it must be something else? Works without problems on a real beacon.

**Comment by dermike** [comment]
Same problem with other custom bitly domains.
http://birch.ly/1VAcmLZ doesn't advertise correctly, but http://bit.ly/1VAcmLZ does. 

This makes it look like it's got nothing to do with advertising, but the custom domains work fine on real beacons.

**Comment by sandeepmistry** [comment]
@dermike were you using it on OS X?

Try the latest, http://nigh.pw/1LPkaFc and http://birch.ly/1VAcmLZ work for me.

OS X was adding an extra set of GAP flags to the advertisement, I've made some changes to remove it.

**Comment by dermike** [comment]
Yes, OS X. Will try the new one, thanks!

**Comment by sandeepmistry** [comment]
Ok, I just pushed the changes to Github, will be publishing v1.0 to npm later today.

Feedback is welcome!

**Comment by sandeepmistry** [comment]
@dermike can we close this?

**Comment by dermike** [comment]
I guess so, can't test myself until tomorrow, I believe you it's fixed ;)

**Comment by sandeepmistry** [comment]
@dermike sounds good, once you've tested, I think it's ready to publish version 1.0 to npm :)

**Comment by dermike** [comment]
@sandeepmistry working, ship it! :)

**Comment by sandeepmistry** [comment]
@dermike sweet, version 1.0 published to npm.

**Comment by ragingwind** [comment]
@sandeepmistry Thank for great job!
