### ISSUE TITLE
node-eddystone-beacon on RaspberryPi implementation

### ISSUE THREAD

**Issue by razvanstanga** [don/node-eddystone-beacon#16]
https://github.com/razvanstanga/piBeacon

I will soon create the backend app used to manage campaigns on piBeacon's.

**Comment by sandeepmistry** [comment]
@razvanstanga cool!

Is there anything you'd like us to do with this?

**Comment by razvanstanga** [comment]
No, thank you :) I wanted to let non technical people that want to try node-eddystone-beacon know there is an easy solution to have beacons with opensource software on Raspberry Pi.
I am waiting for beacon.advertiseUid :) LE : nevermind :)

**Comment by sandeepmistry** [comment]
@razvanstanga yes, just pushed some changes for `advertiseUid` earlier today.

Feel free to submit a PR with a link to your project in the read me once you are ready.
