### ISSUE TITLE
powerlevel doesn't seem to effect range. 

### ISSUE THREAD

**Issue by craigmulligan** [don/node-eddystone-beacon#19]
Hi :)

I'm trying to make a hyper-localized beacon. So I have tried to change the txPowerLevel you suggest in this example. https://github.com/don/node-eddystone-beacon/blob/master/examples/url/power-level.js 

I'm using googles physicalweb app to detect the beacons broadcast, and it seems to be picking up the beacon's url at the same distance (8m) regardless what I set the txPowerLevel. 

Thanks in advance, 
Craig

**Comment by sandeepmistry** [comment]
Hey @craig-mulligan,

The TX power level is for the **measured** value at 0m away (see https://github.com/google/eddystone/tree/master/eddystone-url#tx-power-level).

If you're using this library on Linux, you can try to adjust the TX power level with the following command:

``` sh
sudo hciconfig hci0 inqtpl 0
```

and use the following command to read the current level:

``` sh
sudo hciconfig hci0 inqtpl
```

However, the set command doesn't seem to do anything on the Broadcom and CSR USB Bluetooth 4.0 adapters I own. The power levels remain fixed and 0 and 4 respectively.

Anybody know of a way to set the TX power level on Linux?

**Comment by sandeepmistry** [comment]
Based on https://github.com/sandeepmistry/bleno/issues/125, it doesn't look like this is possible. So closing.

**Comment by jcampbell05** [comment]
Is possible on CSR but with the bccm command

**Comment by shotahino** [comment]
@jcampbell05 What is the command we should use?
For example, if we want to set Tx transmit power to X dBm, what command should we use?

**Comment by edweip3** [comment]
anyone figured out the bccm command for CSR to use to lower the TX power level?
