### ISSUE TITLE
Ability to customize transmit power level

### ISSUE THREAD

**Issue by dinhvh** [don/node-eddystone-beacon#2]
For now, a default value of 32 is send in the advertising packet, which is a very high transmit power level.
We should be able to change that, depending on the hardware we're using.

It could be provided through an additional optional parameter of uriBeacon.advertise().
For example:

```
uriBeacon.advertise('http://example.com', {txPowerLevel: -22})
```

**Comment by don** [comment]
@dinhviethoa that's a great suggestion, I'll make tx power configurable.

Do you have a suggested saner default tx power to use in place of 0x20?

**Comment by dinhvh** [comment]
We use -22 on our CSR beacons and Blesh is using -31.
