### ISSUE TITLE
failed to install with npm on raspberry pi

### ISSUE THREAD

**Issue by paultanner** [don/node-eddystone-beacon#20]
Hi,

I am running Linux raspberrypi 3.12.28+ and when I try to install i get 

```
npm http GET https://registry.npmjs.org/eddystone-beacon
npm http 304 https://registry.npmjs.org/eddystone-beacon
npm http GET https://registry.npmjs.org/bleno
npm http GET https://registry.npmjs.org/eddystone-url-encoding
npm http 304 https://registry.npmjs.org/eddystone-url-encoding
npm http 304 https://registry.npmjs.org/bleno
npm ERR! Error: No compatible version found: eddystone-url-encoding@'^1.0.0'
npm ERR! Valid install targets:
npm ERR! ["1.0.0"]
etc...
```

is there a better way to install?

Thx. Regards, Paul

**Comment by craigmulligan** [comment]
Hey @paultanner, 

You usually run into issues like that when your version of npm or node is out of date. Have you tried updating them to the latest versions? 

If your interested I've gotten it working on RPI using resin.io. You can see my project it here - https://github.com/craig-mulligan/re-eddy.

**Comment by paultanner** [comment]
Thx Craig,

Duh. I think I've come across that before and the 304 throws me.  I had updated a lot of stuff but not npm.  Have now.  And all working nicely as an Eddystone beacon.
And thx for link to your project on resin.

Paul

**Comment by craigmulligan** [comment]
Great @paultanner! 

If you get a chance could you test the txpowerlevel arg I mentioned here - https://github.com/don/node-eddystone-beacon/issues/19? Changing it doesn't seem to make a difference for me but I maybe be missing something. 

Cheers!
