### ISSUE TITLE
Is library currently expected to support multiple beacons at the same time?

### ISSUE THREAD

**Issue by jacobrosenthal** [don/node-eddystone-beacon#21]
I believe bleno supports creating multiple peripherals? And eddystone-beacon seems to return a new instance. Should you be able to make multiple beacons? The following code only advertises whatever it was last called with:

``` js
var eddystoneBeacon = require('./../../index');

eddystoneBeacon.advertiseUid('00010203040506070809', 'aabbccddeeff');

setTimeout(function(){

  var eddystoneBeacon2 = require('./../../index');
  eddystoneBeacon2.advertiseUrl('http://www.google.com');

},10000);
```

**Comment by sandeepmistry** [comment]
@jacobrosenthal that's the expected behaviour. Only one advertisement at a time.

Only TLM interleaving is currently supported.

**Comment by jacobrosenthal** [comment]
I have no urgent need for multiple devices currently, but who is the
blocker bleno or eddystone-beacon?

**Comment by sandeepmistry** [comment]
I wouldn't say it's a blocker, the radio can only have a single advertisement data at a time, so the bleno API has this in mind.

The eddystone-beacon uses a timer to rotate the advertising data, so for multiple advertising frame types to be interleaved, a similar approach is needed.
