### ISSUE TITLE
Advertising URL does not work with Windows

### ISSUE THREAD

**Issue by timukasr** [don/node-eddystone-beacon#29]
I tried the Eddystone-URL example on my Windows machine and I got error: Your platform is not supported!
I tried to debug it and found, that `bleno` has platform check:

``` javascript
if (platform === 'linux') {
  // Linux only API
  Bleno.prototype.startAdvertisingWithEIRData = function(advertisementData, scanData, callback) {
    if (callback) {
      this.once('advertisingStart', callback);
    }
    this._bindings.startAdvertisingWithEIRData(advertisementData, scanData);
  };
}
```

When I commented out the linux check, the URl advertising worked well enough on Windows. Also, the newer version of bleno has removed the check (https://github.com/sandeepmistry/bleno/commit/ff5025be8101c01f11d2fbff03b80d2dd321213e).

Can I get the module working on Windows without modifiying the source code or do you need to update dependencies etc?

Node: 5.0.0
NPM: 3.36
Windows: 8.1 Pro

**Comment by sandeepmistry** [comment]
@timukasr I've published v1.0.4 which uses the latest bleno dependency (0.3.2).

Let me know if this works for you.

**Comment by timukasr** [comment]
@sandeepmistry Works fine now. Thank you.

**Comment by sandeepmistry** [comment]
@timukasr awesome, thanks for confirming!
