### ISSUE TITLE
Advertisement hardcoded to 100ms ?

### ISSUE THREAD

**Issue by natcl** [don/node-eddystone-beacon#35]
Is there a reason why the advertisement is harcoded to 100ms ?
For our usage we need to send data faster than that.

Thanks !

**Comment by sandeepmistry** [comment]
@natcl this is because [bleno](https://github.com/sandeepmistry/bleno) has a fixed interval on 100ms.

OS X does not allow you to control the advertising interval, so a compromise was to fix it to 100ms for all platforms.

**Comment by natcl** [comment]
Thanks, was able to change the Advertising interval using this:

```
sudo BLENO_ADVERTISING_INTERVAL=500 node <your file>.js
```
