### ISSUE TITLE
LIBUSB_TRANSFER_STALL or LIBUSB_TRANSFER_ERROR using connectable.js example

### ISSUE THREAD

**Issue by rajsite** [don/node-eddystone-beacon#38]
On Windows 10 I can run most of the examples in examples/url and have an eddystone-beacon url broadcasting. When I run the examples/connectable demo, the url is advertised correctly however when trying to connect to the device I get one of the following two errors:

```
on -> advertisingStart
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: LIBUSB_TRANSFER_STALL
    at Error (native)

```

or

```
n -> advertisingStart
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: LIBUSB_TRANSFER_ERROR
    at Error (native)
```

After which node exits and url broadcasting stops. Even if I use a non-connecting example (ie examples/url/simple) if a connection is attempted one of those two errors occur.

PC Environment:
Windows 10 64-bit
node v4.3.2 32-bit
eddystone-beacon 1.0.6
CSR8510 A10 USB BLE Adapter
Visual Studio Community 2015
python 2.7.5

Mobile Environment:
Nexus 5X
Android BLE Scanner app for testing connection

**Comment by rajsite** [comment]
I got a log by doing the following:

```
set DEBUG=*
node connectable.js > log.txt 2>&1

```

[log.txt](https://github.com/don/node-eddystone-beacon/files/205592/log.txt)

**Comment by rajsite** [comment]
I see the same behavior in the following environment:
Windows 7 64-bit
node v4.2.6 64-bit
eddystone-beacon 1.0.6
CSR8510 A10 USB BLE Adapter, WinUSB v6.1.7600.16385
Visual Studio 2013
python 2.7.11

[log-win7.txt](https://github.com/don/node-eddystone-beacon/files/206989/log-win7.txt)

**Comment by sandeepmistry** [comment]
Closing this, as issue has been reported upstream: https://github.com/sandeepmistry/bleno/issues/184
