### ISSUE TITLE
Highsierra support

### ISSUE THREAD

**Issue by hrntknr** [don/node-eddystone-beacon#49]
I tried this module in High sierra, but It didn't work.
It seems that the bug is caused by [bleno bug](https://github.com/noble/bleno/pull/360).
I try updating bleno, it works properly.

**Comment by eric-zeng** [comment]
Hello, would it be possible to create an npm release with the commit that fixes bleno for High Sierra? I noticed that 673788ec fixes the issue, but the latest release on npm doesn't have it yet.

**Comment by dermike** [comment]
@eric-zeng quick hack to make it work in your package.json in the meantime:
`"eddystone-beacon": "https://github.com/don/node-eddystone-beacon/tarball/master"`
